### ISSUE TITLE
Events are not sent or recorded on Braze Dashboard

### ISSUE THREAD

**Issue by IsmailSafadi** [rudderlabs/rudder-integration-braze-ios#1]
I added last SDK integration Rudder-Braze and implement code in App delegate and I added all information needed on Braze destination on rudder dashboard

**Comment by arnabp92** [comment]
Hello @IsmailSafadi ,

To understand the issue better, can you please provide these things:
- Your settings on the dashboard (without exposing your keys)
- Initialisation code for `RudderClient`
- The instrumentation code to fire the event
- Version of `Rudder-Braze` you are using
- Error log you are getting regarding Braze (if any)
- Any `log` that looks suspicious to you and you (optional)

**Comment by IsmailSafadi** [comment]
Its resolved now , thanks
