### ISSUE TITLE
Push Notifications Not Working

### ISSUE THREAD

**Issue by rockyev** [rudderlabs/rudder-integration-braze-ios#39]
I am not able to get push notifications working while using the rudder-integration-braze-ios repo. I can get them working on the basic Braze SDK but once I try to implement this one, the relevant functions inside of my AppDelegate simply don't fire off. Are there any other important steps that might be missing from the instructions provided? I've looked at the example app and I've looked through all the documentation that I can find on this. Are there any examples in Swift available? Are there any known issues with push notifications not working here? Please, any info that you can give me at all would be appreciated. Thank you!

For more detail on my specific implementation, I've outlined it in a Google doc [here](https://docs.google.com/document/d/18a8G3KvNjYRhfIMqbbtLEGpquIH-Em6AIlZMzEhL7Ts/edit?usp=sharing).

**Comment by 1abhishekpandey** [comment]
Based on the offline discussion and confirmation received from your side that this issue has been resolved, we are closing it.
